-- sector_mapping: KSIC(한국표준산업분류)/SIC(미국 SIC) 코드 → 공통 sector_tag 매핑
-- source: 'DART' → KSIC 코드 (2자리 division, 필요시 5자리 상세코드로 override)
-- source: 'EDGAR' → SIC 코드 (2자리 major group, 필요시 4자리 상세코드로 override)
-- 조회 우선순위: 상세코드 exact match > major group/division 코드 prefix match > OTHER

CREATE TABLE IF NOT EXISTS sector_mapping (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source        TEXT NOT NULL CHECK (source IN ('DART', 'EDGAR')),
  original_code TEXT NOT NULL,
  original_name TEXT NOT NULL,
  sector_tag    TEXT NOT NULL CHECK (sector_tag IN (
    'SAAS', 'MANUFACTURING', 'BIOTECH_HEALTHCARE', 'RETAIL_COMMERCE', 'FINANCE',
    'MEDIA_CONTENT', 'HARDWARE_SEMICONDUCTOR', 'ENERGY', 'LOGISTICS_TRANSPORT',
    'CONSUMER_GOODS', 'REAL_ESTATE_CONSTRUCTION', 'OTHER'
  )),
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (source, original_code)
);

-- corp_master: DART KSIC 코드 원본 + 산출된 sector_tag
ALTER TABLE corp_master
  ADD COLUMN IF NOT EXISTS ksic_code  TEXT,
  ADD COLUMN IF NOT EXISTS sector_tag TEXT;

CREATE INDEX IF NOT EXISTS corp_master_sector_tag_idx ON corp_master (sector_tag) WHERE sector_tag IS NOT NULL;

-- cik_master: EDGAR SIC 코드 원본 + 산출된 sector_tag
ALTER TABLE cik_master
  ADD COLUMN IF NOT EXISTS sic_code        TEXT,
  ADD COLUMN IF NOT EXISTS sic_description TEXT,
  ADD COLUMN IF NOT EXISTS sector_tag      TEXT;

CREATE INDEX IF NOT EXISTS cik_master_sector_tag_idx ON cik_master (sector_tag) WHERE sector_tag IS NOT NULL;

-- ── KSIC 10차 개정 — division(2자리) 대분류 매핑 ──────────────────────────────
INSERT INTO sector_mapping (source, original_code, original_name, sector_tag) VALUES
  ('DART', '01', '농업',                                   'CONSUMER_GOODS'),
  ('DART', '02', '임업',                                   'CONSUMER_GOODS'),
  ('DART', '03', '어업',                                   'CONSUMER_GOODS'),
  ('DART', '05', '석탄, 원유 및 천연가스 광업',              'ENERGY'),
  ('DART', '06', '금속 광업',                               'MANUFACTURING'),
  ('DART', '07', '비금속광물 광업; 연료용 제외',            'MANUFACTURING'),
  ('DART', '08', '광업 지원 서비스업',                       'ENERGY'),
  ('DART', '10', '식료품 제조업',                           'CONSUMER_GOODS'),
  ('DART', '11', '음료 제조업',                             'CONSUMER_GOODS'),
  ('DART', '12', '담배 제조업',                             'CONSUMER_GOODS'),
  ('DART', '13', '섬유제품 제조업; 의복 제외',              'CONSUMER_GOODS'),
  ('DART', '14', '의복, 의복액세서리 및 모피제품 제조업',   'CONSUMER_GOODS'),
  ('DART', '15', '가죽, 가방 및 신발 제조업',               'CONSUMER_GOODS'),
  ('DART', '16', '목재 및 나무제품 제조업; 가구 제외',      'MANUFACTURING'),
  ('DART', '17', '펄프, 종이 및 종이제품 제조업',           'MANUFACTURING'),
  ('DART', '18', '인쇄 및 기록매체 복제업',                 'MEDIA_CONTENT'),
  ('DART', '19', '코크스, 연탄 및 석유정제품 제조업',       'ENERGY'),
  ('DART', '20', '화학 물질 및 화학제품 제조업; 의약품 제외', 'MANUFACTURING'),
  ('DART', '21', '의료용 물질 및 의약품 제조업',            'BIOTECH_HEALTHCARE'),
  ('DART', '22', '고무제품 및 플라스틱제품 제조업',         'MANUFACTURING'),
  ('DART', '23', '비금속 광물제품 제조업',                  'MANUFACTURING'),
  ('DART', '24', '1차 금속 제조업',                          'MANUFACTURING'),
  ('DART', '25', '금속가공제품 제조업; 기계 및 가구 제외',  'MANUFACTURING'),
  ('DART', '26', '전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업', 'HARDWARE_SEMICONDUCTOR'),
  ('DART', '27', '의료, 정밀, 광학기기 및 시계 제조업',     'HARDWARE_SEMICONDUCTOR'),
  ('DART', '28', '전기장비 제조업',                          'HARDWARE_SEMICONDUCTOR'),
  ('DART', '29', '기타 기계 및 장비 제조업',                'MANUFACTURING'),
  ('DART', '30', '자동차 및 트레일러 제조업',               'MANUFACTURING'),
  ('DART', '31', '기타 운송장비 제조업',                    'MANUFACTURING'),
  ('DART', '32', '가구 제조업',                              'CONSUMER_GOODS'),
  ('DART', '33', '기타 제품 제조업',                        'CONSUMER_GOODS'),
  ('DART', '34', '산업용 기계 및 장비 수리업',              'MANUFACTURING'),
  ('DART', '35', '전기, 가스, 증기 및 공기조절 공급업',     'ENERGY'),
  ('DART', '36', '수도사업',                                 'ENERGY'),
  ('DART', '37', '하수, 폐수 및 분뇨 처리업',               'ENERGY'),
  ('DART', '38', '폐기물 수집운반, 처리 및 원료재생업',     'ENERGY'),
  ('DART', '39', '환경 정화 및 복원업',                      'ENERGY'),
  ('DART', '41', '종합 건설업',                              'REAL_ESTATE_CONSTRUCTION'),
  ('DART', '42', '전문직별 공사업',                          'REAL_ESTATE_CONSTRUCTION'),
  ('DART', '45', '자동차 및 부품 판매업',                    'RETAIL_COMMERCE'),
  ('DART', '46', '도매 및 상품중개업',                       'RETAIL_COMMERCE'),
  ('DART', '47', '소매업; 자동차 제외',                      'RETAIL_COMMERCE'),
  ('DART', '49', '육상운송 및 파이프라인 운송업',           'LOGISTICS_TRANSPORT'),
  ('DART', '50', '수상 운송업',                              'LOGISTICS_TRANSPORT'),
  ('DART', '51', '항공 운송업',                              'LOGISTICS_TRANSPORT'),
  ('DART', '52', '창고 및 운송관련 서비스업',                'LOGISTICS_TRANSPORT'),
  ('DART', '55', '숙박업',                                   'RETAIL_COMMERCE'),
  ('DART', '56', '음식점 및 주점업',                         'RETAIL_COMMERCE'),
  ('DART', '58', '출판업',                                   'MEDIA_CONTENT'),
  ('DART', '59', '영상·오디오 기록물 제작 및 배급업',       'MEDIA_CONTENT'),
  ('DART', '60', '방송업',                                   'MEDIA_CONTENT'),
  ('DART', '61', '통신업',                                   'OTHER'),
  ('DART', '62', '컴퓨터 프로그래밍, 시스템 통합 및 관리업', 'SAAS'),
  ('DART', '63', '정보서비스업',                              'SAAS'),
  ('DART', '64', '금융업',                                   'FINANCE'),
  ('DART', '65', '보험 및 연금업',                           'FINANCE'),
  ('DART', '66', '금융 및 보험 관련 서비스업',               'FINANCE'),
  ('DART', '68', '부동산업',                                 'REAL_ESTATE_CONSTRUCTION'),
  ('DART', '70', '연구개발업',                               'OTHER'),
  ('DART', '71', '전문서비스업',                             'OTHER'),
  ('DART', '72', '건축기술, 엔지니어링 및 기타 과학기술 서비스업', 'REAL_ESTATE_CONSTRUCTION'),
  ('DART', '73', '기타 전문, 과학 및 기술 서비스업',        'OTHER'),
  ('DART', '74', '사업시설 관리 및 조경 서비스업',           'OTHER'),
  ('DART', '75', '사업지원 서비스업',                        'OTHER'),
  ('DART', '84', '공공행정, 국방 및 사회보장 행정',         'OTHER'),
  ('DART', '85', '교육 서비스업',                            'OTHER'),
  ('DART', '86', '보건업',                                   'BIOTECH_HEALTHCARE'),
  ('DART', '87', '사회복지 서비스업',                        'BIOTECH_HEALTHCARE'),
  ('DART', '90', '창작, 예술 및 여가관련 서비스업',         'MEDIA_CONTENT'),
  ('DART', '91', '스포츠 및 오락관련 서비스업',              'MEDIA_CONTENT'),
  ('DART', '94', '협회 및 단체',                             'OTHER'),
  ('DART', '95', '개인 및 소비용품 수리업',                  'OTHER'),
  ('DART', '96', '기타 개인 서비스업',                        'OTHER'),
  ('DART', '97', '가구 내 고용활동',                          'OTHER'),
  ('DART', '99', '국제 및 외국기관',                          'OTHER')
ON CONFLICT (source, original_code) DO NOTHING;

-- ── SIC — major group(2자리) 매핑 ────────────────────────────────────────────
INSERT INTO sector_mapping (source, original_code, original_name, sector_tag) VALUES
  ('EDGAR', '01', 'Agriculture, forestry, fishing',                     'CONSUMER_GOODS'),
  ('EDGAR', '10', 'Metal mining',                                        'ENERGY'),
  ('EDGAR', '12', 'Coal mining',                                         'ENERGY'),
  ('EDGAR', '13', 'Oil and gas extraction',                              'ENERGY'),
  ('EDGAR', '14', 'Mining and quarrying of nonmetallic minerals',        'MANUFACTURING'),
  ('EDGAR', '15', 'Building construction',                               'REAL_ESTATE_CONSTRUCTION'),
  ('EDGAR', '16', 'Heavy construction',                                  'REAL_ESTATE_CONSTRUCTION'),
  ('EDGAR', '17', 'Construction - special trade contractors',           'REAL_ESTATE_CONSTRUCTION'),
  ('EDGAR', '20', 'Food and kindred products',                          'CONSUMER_GOODS'),
  ('EDGAR', '21', 'Tobacco products',                                    'CONSUMER_GOODS'),
  ('EDGAR', '22', 'Textile mill products',                              'CONSUMER_GOODS'),
  ('EDGAR', '23', 'Apparel and other finished products',                'CONSUMER_GOODS'),
  ('EDGAR', '24', 'Lumber and wood products',                           'MANUFACTURING'),
  ('EDGAR', '25', 'Furniture and fixtures',                             'CONSUMER_GOODS'),
  ('EDGAR', '26', 'Paper and allied products',                          'MANUFACTURING'),
  ('EDGAR', '27', 'Printing, publishing and allied industries',         'MEDIA_CONTENT'),
  ('EDGAR', '28', 'Chemicals and allied products',                      'MANUFACTURING'),
  ('EDGAR', '29', 'Petroleum refining and related industries',          'ENERGY'),
  ('EDGAR', '30', 'Rubber and misc plastics products',                  'MANUFACTURING'),
  ('EDGAR', '31', 'Leather and leather products',                       'CONSUMER_GOODS'),
  ('EDGAR', '32', 'Stone, clay, glass and concrete products',           'MANUFACTURING'),
  ('EDGAR', '33', 'Primary metal industries',                           'MANUFACTURING'),
  ('EDGAR', '34', 'Fabricated metal products',                          'MANUFACTURING'),
  ('EDGAR', '35', 'Industrial and commercial machinery',                'MANUFACTURING'),
  ('EDGAR', '36', 'Electronic and other electrical equipment',          'HARDWARE_SEMICONDUCTOR'),
  ('EDGAR', '37', 'Transportation equipment',                           'MANUFACTURING'),
  ('EDGAR', '38', 'Measuring, analyzing, controlling instruments',      'HARDWARE_SEMICONDUCTOR'),
  ('EDGAR', '39', 'Miscellaneous manufacturing industries',             'MANUFACTURING'),
  ('EDGAR', '40', 'Railroad transportation',                            'LOGISTICS_TRANSPORT'),
  ('EDGAR', '41', 'Local and interurban passenger transit',             'LOGISTICS_TRANSPORT'),
  ('EDGAR', '42', 'Trucking and warehousing',                           'LOGISTICS_TRANSPORT'),
  ('EDGAR', '43', 'US Postal Service',                                  'LOGISTICS_TRANSPORT'),
  ('EDGAR', '44', 'Water transportation',                               'LOGISTICS_TRANSPORT'),
  ('EDGAR', '45', 'Transportation by air',                              'LOGISTICS_TRANSPORT'),
  ('EDGAR', '46', 'Pipelines, except natural gas',                      'ENERGY'),
  ('EDGAR', '47', 'Transportation services',                            'LOGISTICS_TRANSPORT'),
  ('EDGAR', '48', 'Communications',                                     'OTHER'),
  ('EDGAR', '49', 'Electric, gas and sanitary services',                'ENERGY'),
  ('EDGAR', '50', 'Wholesale trade - durable goods',                    'RETAIL_COMMERCE'),
  ('EDGAR', '51', 'Wholesale trade - non-durable goods',                'RETAIL_COMMERCE'),
  ('EDGAR', '52', 'Retail - building materials, hardware',              'RETAIL_COMMERCE'),
  ('EDGAR', '53', 'Retail - general merchandise stores',                'RETAIL_COMMERCE'),
  ('EDGAR', '54', 'Retail - food stores',                               'RETAIL_COMMERCE'),
  ('EDGAR', '55', 'Retail - automotive dealers and gas stations',       'RETAIL_COMMERCE'),
  ('EDGAR', '56', 'Retail - apparel and accessory stores',              'RETAIL_COMMERCE'),
  ('EDGAR', '57', 'Retail - furniture and homefurnishings stores',      'RETAIL_COMMERCE'),
  ('EDGAR', '58', 'Retail - eating and drinking places',                'RETAIL_COMMERCE'),
  ('EDGAR', '59', 'Retail stores, not elsewhere classified',            'RETAIL_COMMERCE'),
  ('EDGAR', '60', 'Depository institutions (banks)',                    'FINANCE'),
  ('EDGAR', '61', 'Non-depository credit institutions',                 'FINANCE'),
  ('EDGAR', '62', 'Security and commodity brokers, dealers',            'FINANCE'),
  ('EDGAR', '63', 'Insurance',                                          'FINANCE'),
  ('EDGAR', '64', 'Insurance agents, brokers and service',              'FINANCE'),
  ('EDGAR', '65', 'Real estate',                                        'REAL_ESTATE_CONSTRUCTION'),
  ('EDGAR', '67', 'Holding and other investment offices',               'FINANCE'),
  ('EDGAR', '70', 'Hotels, rooming houses, camps and lodging places',   'RETAIL_COMMERCE'),
  ('EDGAR', '72', 'Personal services',                                  'OTHER'),
  ('EDGAR', '73', 'Business services',                                  'OTHER'),
  ('EDGAR', '75', 'Automotive repair, services and parking',            'OTHER'),
  ('EDGAR', '76', 'Miscellaneous repair services',                      'OTHER'),
  ('EDGAR', '78', 'Motion pictures',                                    'MEDIA_CONTENT'),
  ('EDGAR', '79', 'Amusement and recreation services',                  'MEDIA_CONTENT'),
  ('EDGAR', '80', 'Health services',                                    'BIOTECH_HEALTHCARE'),
  ('EDGAR', '81', 'Legal services',                                     'OTHER'),
  ('EDGAR', '82', 'Educational services',                               'OTHER'),
  ('EDGAR', '83', 'Social services',                                    'OTHER'),
  ('EDGAR', '84', 'Museums, botanical, zoological gardens',             'MEDIA_CONTENT'),
  ('EDGAR', '86', 'Membership organizations',                           'OTHER'),
  ('EDGAR', '87', 'Engineering, accounting, research, management services', 'OTHER'),
  ('EDGAR', '88', 'Private households',                                 'OTHER'),
  ('EDGAR', '89', 'Services, not elsewhere classified',                 'OTHER'),
  ('EDGAR', '91', 'Executive, legislative, general government',        'OTHER'),
  ('EDGAR', '92', 'Justice, public order and safety',                  'OTHER'),
  ('EDGAR', '93', 'Public finance, taxation, monetary policy',         'FINANCE'),
  ('EDGAR', '94', 'Administration of human resource programs',        'OTHER'),
  ('EDGAR', '95', 'Administration of environmental programs',         'OTHER'),
  ('EDGAR', '96', 'Administration of economic programs',               'OTHER'),
  ('EDGAR', '97', 'National security and international affairs',      'OTHER'),
  ('EDGAR', '99', 'Nonclassifiable establishments',                    'OTHER')
ON CONFLICT (source, original_code) DO NOTHING;

-- ── SIC — 4자리 상세코드 override (2자리 major group보다 우선 조회) ──────────
-- 제약/바이오 (major group 28 화학 산하지만 의약품은 별도 분류)
INSERT INTO sector_mapping (source, original_code, original_name, sector_tag) VALUES
  ('EDGAR', '2833', 'Medicinal chemicals and botanical products',       'BIOTECH_HEALTHCARE'),
  ('EDGAR', '2834', 'Pharmaceutical preparations',                       'BIOTECH_HEALTHCARE'),
  ('EDGAR', '2835', 'In vitro and in vivo diagnostic substances',        'BIOTECH_HEALTHCARE'),
  ('EDGAR', '2836', 'Biological products',                               'BIOTECH_HEALTHCARE'),
  ('EDGAR', '8731', 'Commercial physical and biological research',       'BIOTECH_HEALTHCARE'),
  ('EDGAR', '3826', 'Laboratory analytical instruments',                 'BIOTECH_HEALTHCARE'),
  ('EDGAR', '3841', 'Surgical and medical instruments',                  'BIOTECH_HEALTHCARE'),
  ('EDGAR', '3842', 'Orthopedic, prosthetic and surgical appliances',    'BIOTECH_HEALTHCARE'),
  ('EDGAR', '3845', 'Electromedical and electrotherapeutic apparatus',   'BIOTECH_HEALTHCARE'),
  -- 소프트웨어/IT서비스 (major group 73 Business services 산하)
  ('EDGAR', '7370', 'Services-computer programming, data processing',   'SAAS'),
  ('EDGAR', '7371', 'Computer programming services',                    'SAAS'),
  ('EDGAR', '7372', 'Prepackaged software',                             'SAAS'),
  ('EDGAR', '7373', 'Computer integrated systems design',               'SAAS'),
  ('EDGAR', '7374', 'Computer processing and data preparation',         'SAAS'),
  ('EDGAR', '7375', 'Information retrieval services',                   'SAAS'),
  ('EDGAR', '7376', 'Computer facilities management services',          'SAAS'),
  ('EDGAR', '7379', 'Computer related services, NEC',                   'SAAS'),
  -- 반도체/전자 (major group 36 산하)
  ('EDGAR', '3674', 'Semiconductors and related devices',               'HARDWARE_SEMICONDUCTOR'),
  ('EDGAR', '3571', 'Electronic computers',                             'HARDWARE_SEMICONDUCTOR'),
  ('EDGAR', '3576', 'Computer communications equipment',                'HARDWARE_SEMICONDUCTOR'),
  -- 방송/미디어 (major group 48 산하)
  ('EDGAR', '4832', 'Radio broadcasting stations',                      'MEDIA_CONTENT'),
  ('EDGAR', '4833', 'Television broadcasting stations',                 'MEDIA_CONTENT'),
  ('EDGAR', '4841', 'Cable and other pay television services',         'MEDIA_CONTENT'),
  -- 인터넷 서비스 (major group 73/48 혼재 — 최신 EDGAR 관행상 별도 코드 사용)
  ('EDGAR', '7812', 'Motion picture and video tape production',        'MEDIA_CONTENT'),
  ('EDGAR', '7819', 'Services allied to motion picture production',    'MEDIA_CONTENT'),
  ('EDGAR', '7822', 'Motion picture and video tape distribution',      'MEDIA_CONTENT')
ON CONFLICT (source, original_code) DO NOTHING;
